title: Oluwatosin Olagunju
logo: Oluwatosin.png
description: Data Analyst with 2 years experience and highly skilled in Microsoft Exce, Powerbi, and SQL
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
